cjdns:
  ip4_range: 10.66.6.0/24
  ip4_allocations_per_client: 32  # ip4_range prefix (24) to 32
  ip4_network_size: 0  # number between 0 and ip4_allocation_per_client
  # ip6_range: 2c0f:f930:0002::/48
  # ip6_allocations_per_client: 64  # ip6_range prefix (48) to 128
  # ip6_network_size: 0  # 0 to ip6_allocation_per_client
api_server:
  port: 8888
