openapi: 3.0.1
info:
  title: Anode VPN Server
  description: 'VPN server for Anode at [http://localhost](http://localhost)'
  termsOfService: 'http://anode.co/terms/'
  contact:
    email: info@anode.co
  version: "1.0"
externalDocs:
  description: Find out more about Anode
  url: 'http://anode.co'
servers:
  - url: 'https://localhost:8888/'
tags:
  - name: Authorize
    description: 'Authorize clients on the VPN'
    externalDocs:
      description: Find out more
      url: 'http://api.anode.co'
paths:
  /api/0.3/server/authorize/:
    post:
      tags:
        - Authorize
      summary: Authorize cjdns public key
      description: Client requests authorization from VPN server for access to the VPN, including active network routes and IP address allocation.
      operationId: addClientAuthorization
      requestBody:
        description: Client public key
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicKeyInput'
        required: true
      responses:
        '201':
          description: Created. New client authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '200':
          description: OK. Authorization extended
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '403':
          description: Forbidden. This cilent is not authorized to connect
        '407':
          description: Proxy Authentication Failed. The coordinaton server signature could not be verified
        '500':
          description: Server Error. Response for all other errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '503':
          description: Service Unavailable. No more IP addresses for allocation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /api/0.3/server/authorize/{clientPublicKey}:
    delete:
      tags:
        - Authorize
      summary: Remove authorized public key
      description: Remove authorization for a client public key
      operationId: removeClientAuthorization
      parameters:
        - in: path
          name: clientPublicKey
          schema:
            type: string
            example: lbqr0rzyc2tuysw3w8gfr95u68kujzlq7zht5hyf452u8yshr120.k
          description: authorized client cjdns public key
          required: true
      responses:
        '200':
          description: OK. Authorization removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
components:
  schemas:
    StatusResponse:
      type: object
      properties:
        status:
          type: string
          example: 'success'
          enum:
            - success
            - error
          description: >
            Status:
              * `success` - Method completed successfully
              * `error` - Error processing request
        message:
          type: string
          example: 'not found'
          description: Human readable text describing the nature of the status
        expiresAt:
          type: string
          format:  integer
          example: '1591963516'
          description: Unix timestamp representing the date and time the authorization and allocated IP addresses expires
        date:
          type: string
          format: integer
          example: '1591963441'
          description: Unix-timestamp of response
    PublicKeyInput:
      type: object
      properties:
        clientPublicKey:
          type: string
          example: skZ6UtW5u09lHNsj6tQ51s1SPrCBkedbNf0Tp0GbMJDyR4e9T04ZZwIDAQAB.k
          description: A cjdns client's public key
  

